# Generated by Django 4.1 on 2022-08-29 12:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('unit_cost', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=200)),
                ('i_hash', models.CharField(max_length=1064)),
                ('client_name', models.CharField(max_length=200)),
                ('client_addr', models.TextField()),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('Subtotal', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('total', models.IntegerField()),
                ('invoice_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoicedetail')),
            ],
        ),
    ]
